CREATE DATABASE IF NOT EXISTS romromm_test;
CREATE USER IF NOT EXISTS 'romromm_test'@'%' IDENTIFIED BY 'passwd';
GRANT ALL PRIVILEGES ON romromm_test.* TO 'romromm_test'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

